In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/AI, Data Science & Analytics/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [ ]:
df.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [ ]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [ ]:
df.dropna(how = 'any', inplace = True)

In [ ]:
X=df.drop(['customerID', 'Churn'], axis=1)

In [ ]:
y=df.Churn.values

In [ ]:
X

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL             No          Yes   
1                   No             DSL            Yes           No   
2                   No             DSL            Yes          Yes   
3     No phone service             DSL            Yes           No   
4                   No     Fiber optic             No           No   
...                ...             ...            ...          ...   
7038               Yes             DSL            Yes           No   
7039               Yes     Fiber optic             No          Yes   
7040  No phone service             DSL            Yes           No   
7041               Yes     Fiber optic             No           No   
7042                No     Fiber optic            Yes           No   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  
0                 Yes           Electronic check           29.85         29.85  
1                  No               Mailed check           56.95       1889.50  
2                 Yes               Mailed check           53.85        108.15  
3                  No  Bank transfer (automatic)           42.30       1840.75  
4                 Yes           Electronic check           70.70        151.65  
...               ...                        ...             ...           ...  
7038              Yes               Mailed check           84.80       1990.50  
7039              Yes    Credit card (automatic)          103.20       7362.90  
7040              Yes           Electronic check           29.60        346.45  
7041              Yes               Mailed check           74.40        306.60  
7042              Yes  Bank transfer (automatic)          105.65       6844.50  

[7032 rows x 19 columns]

In [ ]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [ ]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [ ]:
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents', 'PhoneService', 
                           'MultipleLines', 'InternetService', 'OnlineSecurity', 
                           'OnlineBackup', 'DeviceProtection', 'TechSupport', 
                           'StreamingTV', 'StreamingMovies', 'Contract', 
                           'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [ ]:
#Splitting the data into training & test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [ ]:
len(X_train)

5274

In [ ]:
len(X_test)

1758

In [ ]:
len(X)

7032

In [ ]:
X_train

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Male  \
5308              0      69           82.45       5555.30            0   
950               1       2           44.95         85.15            1   
1413              0      65           94.55       6078.75            1   
4902              0      24           56.35       1381.20            0   
2689              1      72          116.75       8277.05            0   
...             ...     ...             ...           ...          ...   
4991              0      58          106.45       6145.85            0   
2745              1       1           86.05         86.05            1   
4932              0      27           80.65       2209.75            1   
2601              0      72           98.65       7129.45            0   
75                1      56          110.50       6139.50            0   

      Partner_Yes  Dependents_Yes  PhoneService_Yes  \
5308            0               0                 1   
950             0               0                 1   
1413            1               1                 1   
4902            0               0                 1   
2689            1               0                 1   
...           ...             ...               ...   
4991            0               0                 1   
2745            1               0                 1   
4932            1               1                 1   
2601            1               1                 1   
75              0               0                 1   

      MultipleLines_No phone service  MultipleLines_Yes  ...  \
5308                               0                  0  ...   
950                                0                  0  ...   
1413                               0                  1  ...   
4902                               0                  0  ...   
2689                               0                  1  ...   
...                              ...                ...  ...   
4991                               0                  0  ...   
2745                               0                  1  ...   
4932                               0                  0  ...   
2601                               0                  1  ...   
75                                 0                  1  ...   

      StreamingTV_No internet service  StreamingTV_Yes  \
5308                                0                1   
950                                 0                0   
1413                                0                0   
4902                                0                0   
2689                                0                1   
...                               ...              ...   
4991                                0                1   
2745                                0                1   
4932                                0                0   
2601                                0                0   
75                                  0                1   

      StreamingMovies_No internet service  StreamingMovies_Yes  \
5308                                    0                    1   
950                                     0                    0   
1413                                    0                    0   
4902                                    0                    0   
2689                                    0                    1   
...                                   ...                  ...   
4991                                    0                    1   
2745                                    0                    0   
4932                                    0                    0   
2601                                    0                    1   
75                                      0                    1   

      Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
5308                  0                  1                     1   
950                   0                  0                   

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

#fit_transform for training, and transform for test --> We fit the training data for model building

In [ ]:
X_train_sc

array([[-0.43679284,  1.49723485,  0.59112608, ...,  1.8947502 ,
        -0.70861565, -0.54272535],
       [ 2.2894148 , -1.23544206, -0.6594625 , ..., -0.52777406,
        -0.70861565,  1.84255258],
       [-0.43679284,  1.33408996,  0.99464933, ...,  1.8947502 ,
        -0.70861565, -0.54272535],
       ...,
       [-0.43679284, -0.21578649,  0.53109783, ...,  1.8947502 ,
        -0.70861565, -0.54272535],
       [-0.43679284,  1.61959352,  1.13138034, ..., -0.52777406,
        -0.70861565, -0.54272535],
       [ 2.2894148 ,  0.96701396,  1.52656633, ..., -0.52777406,
         1.41120224, -0.54272535]])

In [ ]:
X_test_sc

array([[-0.43679284, -0.74600739,  0.68116846, ..., -0.52777406,
         1.41120224, -0.54272535],
       [-0.43679284, -0.41971761, -0.50939187, ...,  1.8947502 ,
        -0.70861565, -0.54272535],
       [-0.43679284, -1.23544206,  0.71618494, ..., -0.52777406,
        -0.70861565,  1.84255258],
       ...,
       [-0.43679284,  1.08937263,  1.21308546, ..., -0.52777406,
         1.41120224, -0.54272535],
       [-0.43679284,  0.80386907, -0.02749841, ...,  1.8947502 ,
        -0.70861565, -0.54272535],
       [-0.43679284,  0.23286195, -1.48818586, ..., -0.52777406,
        -0.70861565,  1.84255258]])

In [ ]:
#Call the kNN Classifier
from sklearn.neighbors import KNeighborsClassifier
#Initiating the classifier
model = KNeighborsClassifier()
#Passing the data to the classifier
model.fit(X_train_sc, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = model.predict(X_test_sc)

In [ ]:
y_pred

array(['Yes', 'No', 'Yes', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
y_test

array(['Yes', 'No', 'Yes', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#Classification Metrics - To check the final results
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

result1 = accuracy_score(y_test, y_pred)
print('Accuracy is: ', result1*100)

Accuracy is:  76.79180887372013


In [ ]:
print(confusion_matrix(y_test, y_pred))

[[1110  197]
 [ 211  240]]


### New data prediction

In [ ]:
X_test[2:3].values

array([[  0. ,   2. ,  86.2, 178.7,   0. ,   0. ,   0. ,   1. ,   0. ,
          0. ,   1. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   1. ,
          0. ,   0. ,   0. ,   0. ,   0. ,   1. ,   0. ,   0. ,   1. ,
          0. ,   0. ,   1. ]])

In [ ]:
# Need to pass the data

data = [[...................]]

In [ ]:
data = [[-0.43401975, -1.27708795,  0.46902206, -0.96798926, -1.00570455,
        -0.96533317,  1.51874391,  0.32362629, -0.32362629, -0.85458467,
         1.13013365, -0.53158964, -0.53158964, -0.62750555, -0.53158964,
        -0.7161765 , -0.53158964, -0.72042294, -0.53158964, -0.63367288,
        -0.53158964, -0.78189879, -0.53158964,  1.26565188, -0.51542094,
        -0.56202159, -1.20494101, -0.51483159,  1.38865875, -0.54184706]]

single = model.predict(data)

print(single)

['Yes']


In [ ]:
data2 = [[  0. ,   2. ,  86.2, 178.7,   0. ,   0. ,   0. ,   1. ,   0. ,
          0. ,   1. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   1. ,
          0. ,   0. ,   0. ,   0. ,   0. ,   1. ,   0. ,   0. ,   1. ,
          0. ,   0. ,   1. ]]

data2_sc = sc.transform(data2)

single2 = model.predict(data2_sc)

print(single2)



['Yes']


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
